// Script para popular o Firestore com todas as unidades do PDF
// Execute: node src/utils/seedUnidades.js (após configurar .env)

import { initializeApp } from 'firebase/app'
import { getFirestore, doc, setDoc } from 'firebase/firestore'

// Configure com suas credenciais antes de executar
const firebaseConfig = {
  apiKey:            process.env.VITE_FIREBASE_API_KEY,
  authDomain:        process.env.VITE_FIREBASE_AUTH_DOMAIN,
  projectId:         process.env.VITE_FIREBASE_PROJECT_ID,
  storageBucket:     process.env.VITE_FIREBASE_STORAGE_BUCKET,
  messagingSenderId: process.env.VITE_FIREBASE_MESSAGING_SENDER_ID,
  appId:             process.env.VITE_FIREBASE_APP_ID,
}

export const UNIDADES = [
  { id: '0001-89', cnpj: '0001-89', nome: 'Arquidiocese de Maceio',                           email: 'rharquidiocesemaceio@gmail.com',           ativa: true },
  { id: '0002-60', cnpj: '0002-60', nome: 'N Sra do Livramento - Centro',                      email: 'igrejalivramento@gmail.com',               ativa: true },
  { id: '0003-40', cnpj: '0003-40', nome: 'São João Batista e Sta Izabel - Jd Petropolis',     email: '',                                         ativa: true },
  { id: '0004-21', cnpj: '0004-21', nome: 'N Sra Rosario',                                     email: 'reitorianossasenhoradorosario@gmail.com',  ativa: true },
  { id: '0005-02', cnpj: '0005-02', nome: 'N Sra das Gracas - Levada',                         email: 'paroquiagracalevada@gmail.com',            ativa: true },
  { id: '0006-93', cnpj: '0006-93', nome: 'São Benedito - Centro',                             email: '',                                         ativa: true },
  { id: '0007-74', cnpj: '0007-74', nome: 'N Sra Mãe do Povo - Jaragua',                      email: '',                                         ativa: true },
  { id: '0008-55', cnpj: '0008-55', nome: 'N Sra Perpetuo Socorro - Vergel',                   email: 'secretariapnps.vergel@gmail.com',          ativa: true },
  { id: '0009-36', cnpj: '0009-36', nome: 'Sto Antonio - Bebedouro',                           email: '',                                         ativa: true },
  { id: '0010-70', cnpj: '0010-70', nome: 'N Sra Bom Parto - Bom Parto',                      email: '',                                         ativa: true },
  { id: '0011-50', cnpj: '0011-50', nome: 'São José Operario - Trapiche',                      email: 'paroquiasaojosetrapiche@gmail.com',        ativa: true },
  { id: '0012-31', cnpj: '0012-31', nome: 'Martirios - Bom Jesus dos - Centro',                email: '',                                         ativa: true },
  { id: '0013-12', cnpj: '0013-12', nome: 'Sta Maria Madalena - União',                        email: 'medeirosg8@hotmail.com',                   ativa: true },
  { id: '0014-01', cnpj: '0014-01', nome: 'N Sra do Pilar - Pilar',                            email: 'peronielferreira@gmail.com',               ativa: true },
  { id: '0015-84', cnpj: '0015-84', nome: 'N Sra das Graças - Murici',                         email: 'igrejamurici@hotmail.com',                 ativa: true },
  { id: '0016-65', cnpj: '0016-65', nome: 'N Sr Bomfim - Poço',                                email: 'senhordobomfimp@gmail.com',                ativa: true },
  { id: '0017-46', cnpj: '0017-46', nome: 'Bom Jesus do Bom Fim - Viçosa',                     email: 'paroquiavicosa@gmail.com',                 ativa: true },
  { id: '0018-27', cnpj: '0018-27', nome: 'Sta Rita de Cassia - Farol',                        email: 'paroquiasantaritamaceio@gmail.com',        ativa: true },
  { id: '0019-08', cnpj: '0019-08', nome: 'Sta Luzia de Siracusa - Tabuleiro',                 email: 'valmirrgaldino@hotmail.com.br',            ativa: true },
  { id: '0020-41', cnpj: '0020-41', nome: 'São Jose Operario - Fernão Velho',                  email: 'padremarivaldo@gmail.com',                 ativa: true },
  { id: '0021-22', cnpj: '0021-22', nome: 'N Sra das Brotas - Atalaia',                        email: 'mdasbrotas02@gmail.com',                   ativa: true },
  { id: '0022-03', cnpj: '0022-03', nome: 'N Sra Conceição - Capela',                          email: 'paroquiadecapela@hotmail.com',             ativa: true },
  { id: '0023-94', cnpj: '0023-94', nome: 'N Sra Conceição - Rio Largo',                       email: 'bacilonmonteirodasilva@gmail.com',         ativa: true },
  { id: '0024-75', cnpj: '0024-75', nome: 'São José - São Jose da Laje',                       email: 'paroquiasaojosepascomlaje@gmail.com',      ativa: true },
  { id: '0025-56', cnpj: '0025-56', nome: 'Sag Coração de Jesus - Rio Largo',                  email: '',                                         ativa: true },
  { id: '0026-37', cnpj: '0026-37', nome: 'Bom Jesus - Matriz Camaragibe',                     email: 'paroquia.sdbmatriz@yahoo.com.br',          ativa: true },
  { id: '0027-18', cnpj: '0027-18', nome: 'N Sra do Carmo - Colonia de Leopoldina',            email: 'sparoquial@gmail.com',                     ativa: true },
  { id: '0029-80', cnpj: '0029-80', nome: 'N Sra da Gloria - Porto de Pedras',                 email: 'antelmolima92@hotmail.com',                ativa: true },
  { id: '0030-13', cnpj: '0030-13', nome: 'Seminário Provincial',                              email: '',                                         ativa: true },
  { id: '0031-02', cnpj: '0031-02', nome: 'N Sra Prazeres - Catedral',                         email: 'catedral.mcz@gmail.com',                   ativa: true },
  { id: '0032-85', cnpj: '0032-85', nome: 'N Sra do Carmo - Salgadinho',                       email: 'pcarmosalgadinho@outlook.com',             ativa: true },
  { id: '0033-66', cnpj: '0033-66', nome: 'Sto Antonio - Maragogi',                            email: 'paroquiamaragogi@gmail.com',               ativa: true },
  { id: '0034-47', cnpj: '0034-47', nome: 'N Sra das Graças - Pitanguinha',                    email: 'j.rochapereira@hotmail.com',               ativa: true },
  { id: '0035-28', cnpj: '0035-28', nome: 'São Pedro Apostolo - Pta Verde',                    email: 'apostolopedro251@gmail.com',               ativa: true },
  { id: '0036-09', cnpj: '0036-09', nome: 'N Sra de Lourdes - Gruta',                          email: 'igrejansralourdes@hotmail.com',            ativa: true },
  { id: '0037-90', cnpj: '0037-90', nome: 'N Sra do Livramento - Cajueiro',                    email: 'paroquia.cajueiro123@gmail.com',           ativa: true },
  { id: '0038-70', cnpj: '0038-70', nome: 'N Sra das Dores - Jacintinho',                      email: 'gen23custodire@gmail.com',                 ativa: true },
  { id: '0039-51', cnpj: '0039-51', nome: 'Divino Espirito Santo - Jatiuca',                   email: 'divinojatiuca@hotmail.com',                ativa: true },
  { id: '0040-95', cnpj: '0040-95', nome: 'São Caetano - Jacuipe',                             email: '',                                         ativa: true },
  { id: '0041-76', cnpj: '0041-76', nome: 'N Sra Conceição - Mal Deodoro',                     email: '',                                         ativa: true },
  { id: '0042-57', cnpj: '0042-57', nome: 'Sta Luzia de Siracusa - Sta Luzia do Norte',        email: '',                                         ativa: true },
  { id: '0043-38', cnpj: '0043-38', nome: 'Menino Jesus do Jardim das Acacias - Farol',        email: 'fazendamourao2@gmail.com',                 ativa: true },
  { id: '0044-19', cnpj: '0044-19', nome: 'São Sebastião - Pindoba',                           email: '',                                         ativa: true },
  { id: '0045-08', cnpj: '0045-08', nome: 'Sta Teresinha de Lisieux - Farol',                  email: 'paroquiauniversitariademaceio@gmail.com',  ativa: true },
  { id: '0048-42', cnpj: '0048-42', nome: 'São Paulo Apostolo - Tabuleiro Novo',               email: 'p.saopauloapostolo@hotmail.com',           ativa: true },
  { id: '0049-23', cnpj: '0049-23', nome: 'Sagrado Coração Jesus - Cruz das Almas',            email: 'pscj.cruzdasalmas@hotmail.com',            ativa: true },
  { id: '0050-67', cnpj: '0050-67', nome: 'São Judas Tadeu - Feitosa',                         email: 'saojudastadeufeitosa@hotmail.com',         ativa: true },
  { id: '0051-48', cnpj: '0051-48', nome: 'Sto Amaro - Paripueira',                            email: '',                                         ativa: true },
  { id: '0052-29', cnpj: '0052-29', nome: 'N Sra Auxiliadora - Eustaq Gomes',                  email: 'mcalvespe@hotmail.com',                    ativa: true },
  { id: '0053-00', cnpj: '0053-00', nome: 'N Sra da Conceição - SL Quitunde',                  email: 'saoluisconceicao@gmail.com',               ativa: true },
  { id: '0054-90', cnpj: '0054-90', nome: 'N Sra da Conceição - Passo',                        email: 'luizantonioguimaraes@gmail.com',           ativa: true },
  { id: '0055-71', cnpj: '0055-71', nome: 'São Jose - Novo Lino',                              email: '',                                         ativa: true },
  { id: '0056-52', cnpj: '0056-52', nome: 'São Maximiliano Kolbe - Benedito Bentes',           email: 'pmkolbemaceio@gmail.com',                  ativa: true },
  { id: '0057-33', cnpj: '0057-33', nome: 'São José e São Benedito - Joaquim Gomes',           email: 'psaojose18@gmail.com',                     ativa: true },
  { id: '0058-14', cnpj: '0058-14', nome: 'N Sra Virgem dos Pobres - Vergel',                  email: 'virgemdospobresmaceio@gmail.com',          ativa: true },
  { id: '0059-03', cnpj: '0059-03', nome: 'Sta Terezinha Menino Jesus - Serraria',             email: '',                                         ativa: true },
  { id: '0060-39', cnpj: '0060-39', nome: 'São Sebastião - Rio Largo',                         email: 'psssoldadoromano@gmail.com',               ativa: true },
  { id: '0061-10', cnpj: '0061-10', nome: 'N Sra Rosa Mistica - Mangabeiras',                  email: 'peantoniomarcos@live.com',                 ativa: true },
  { id: '0062-09', cnpj: '0062-09', nome: 'Sta Catarina de Laboure - Aldebaran',               email: '',                                         ativa: true },
  { id: '0063-81', cnpj: '0063-81', nome: 'São Vicente de Paula - Graciliano Ramos',           email: 'pvicentedepaulo2023@gmail.com',            ativa: true },
  { id: '0064-62', cnpj: '0064-62', nome: 'São João Maria Vianney - Clima Bom I',              email: 'psjmvianney20@gmail.com',                  ativa: true },
  { id: '0065-43', cnpj: '0065-43', nome: 'Imaculada Conceição de N Senhora - Jacintinho',     email: 'imaculadajacintinho@hotmail.com',          ativa: true },
  { id: '0066-24', cnpj: '0066-24', nome: 'Sagrado Coração de Jesus e Maria - Rio Largo',      email: 'paroquiadoiscoracoes@gmail.com',           ativa: true },
  { id: '0067-05', cnpj: '0067-05', nome: 'São João Bosco - Benedito Bentes',                  email: '',                                         ativa: true },
  { id: '0068-96', cnpj: '0068-96', nome: 'São Joao Evangelista - Henrique Equelman',          email: 'evangelistaparoquia@gmail.com',            ativa: true },
  { id: '0069-77', cnpj: '0069-77', nome: 'São Sebastião - Ibateguara',                        email: '',                                         ativa: true },
  { id: '0070-00', cnpj: '0070-00', nome: 'São Benedito - Flexeiras',                          email: 'rod.lima@hotmail.com',                     ativa: true },
  { id: '0071-91', cnpj: '0071-91', nome: 'N Sra Santana - Santana do Mundau',                 email: '',                                         ativa: true },
  { id: '0072-72', cnpj: '0072-72', nome: 'São Pedro Pescador - Frances',                      email: 'saopedropfrances@gmail.com',               ativa: true },
  { id: '0073-53', cnpj: '0073-53', nome: 'N Sra da Guia - Satuba',                            email: 'paroquiansdaguiast@hotmail.com',           ativa: true },
  { id: '0074-34', cnpj: '0074-34', nome: 'N Sra da Conceição - Cha Preta',                   email: '',                                         ativa: true },
  { id: '0075-15', cnpj: '0075-15', nome: 'São Francisco de Assis - Santos Dumont',            email: '',                                         ativa: true },
  { id: '0076-04', cnpj: '0076-04', nome: 'Sta Izabel - Conj Jose Silva Peixoto',              email: 'par.santaisabel@hotmail.com',              ativa: true },
  { id: '0077-87', cnpj: '0077-87', nome: 'N Sra da Conceição - Atalaia',                      email: 'm.francce@gmail.com',                      ativa: true },
  { id: '0078-68', cnpj: '0078-68', nome: 'N Sra Rosa Mistica e Sto Antonio de Padua',         email: 'paroquiarosamistica.maceio@gmail.com',     ativa: true },
  { id: '0079-49', cnpj: '0079-49', nome: 'N Sra Mae do Povo - SM Milagres',                   email: '',                                         ativa: true },
  { id: '0080-82', cnpj: '0080-82', nome: 'N Sra Perpetuo Socorro - Tabuleiro',                email: '',                                         ativa: true },
  { id: '0081-63', cnpj: '0081-63', nome: 'Tribunal Eclesiastico',                             email: '',                                         ativa: true },
  { id: '0082-44', cnpj: '0082-44', nome: 'Sagrada Familia - Cruz das Almas',                  email: 'p.franciscofsa@me.com',                    ativa: true },
  { id: '0083-25', cnpj: '0083-25', nome: 'N Sra do O - Ipioca',                               email: 'francistony57@gmail.com',                  ativa: true },
  { id: '0084-06', cnpj: '0084-06', nome: 'Imaculado Coração de Maria - Gruta',                email: 'imaculadocoracao.rotary@gmail.com',        ativa: true },
  { id: '0085-97', cnpj: '0085-97', nome: 'N Sra da Conceição e Sto Antonio - Barra',         email: 'paroquianscsa@gmail.com',                  ativa: true },
  { id: '0086-78', cnpj: '0086-78', nome: 'N Sra Virgem dos Pobres - Barro Duro',              email: 'contato@virgemdospobres.com.br',           ativa: true },
  { id: '0087-59', cnpj: '0087-59', nome: 'N Sra Aparecida Inocoop',                           email: 'inocoopcatolico@gmail.com',                ativa: true },
  { id: '0088-30', cnpj: '0088-30', nome: 'São Miguel Arcanjo - Sta Amelia',                   email: '',                                         ativa: true },
  { id: '0089-10', cnpj: '0089-10', nome: 'N Sra das Graças - Chã do Pilar',                   email: '',                                         ativa: true },
  { id: '0090-54-santuario', cnpj: '0090-54', nome: 'São Lucas - Santuario',                   email: 'santuarioarquidiocesanovirgem@gmail.com', ativa: true },
  { id: '0090-54-lucas',    cnpj: '0090-54', nome: 'São Lucas',                                email: 'silvaaloisio2@hotmail.com',                ativa: true },
  { id: '0091-35', cnpj: '0091-35', nome: 'Sta Teresinha - Rio Largo',                         email: 'santateresinharl@gmail.com',               ativa: true },
  { id: '0092-16', cnpj: '0092-16', nome: 'N Sra Fatima - Feitosa',                            email: 'paroquiadefatima0518@gmail.com',           ativa: true },
  { id: '0093-05', cnpj: '0093-05', nome: 'N Sra de Lourdes - Rocha Cavalcante União',         email: '',                                         ativa: true },
  { id: '0094-88', cnpj: '0094-88', nome: 'SãoJose - Campestre',                               email: '',                                         ativa: true },
  { id: '0095-69', cnpj: '0095-69', nome: 'N Sra Conceição - Jundiá',                          email: '',                                         ativa: true },
  { id: '0096-40', cnpj: '0096-40', nome: 'N Sra Mãe dos Homens - Coqueiro',                   email: 'p.maedoshomens.cs@gmail.com',              ativa: true },
  { id: '0097-20', cnpj: '0097-20', nome: 'São José - Porto Calvo',                            email: '',                                         ativa: true },
  { id: '0098-01', cnpj: '0098-01', nome: 'Sta Edwiges - Rio largo',                           email: '',                                         ativa: true },
  { id: '0099-92', cnpj: '0099-92', nome: 'São Sebastião - Messias',                           email: '',                                         ativa: true },
  { id: '0100-60', cnpj: '0100-60', nome: 'N Sra da Assunção',                                 email: '',                                         ativa: true },
  { id: '0101-41', cnpj: '0101-41', nome: 'Sta Dulce dos Pobres',                              email: '',                                         ativa: true },
  { id: '0102-22', cnpj: '0102-22', nome: 'QP Imaculado Coração de Maria - Antares',           email: '',                                         ativa: true },
  // Sub-unidades com CNPJ 0001-89
  { id: 'apresentacao',   cnpj: '0001-89', nome: 'N SRA. DA APRESENTAÇÃO',                     email: '',                                         ativa: true },
  { id: 'qp-dores',       cnpj: '0001-89', nome: 'QP N Sra Dores - Sta Lucia',                 email: 'paroquiansdores2010@gmail.com',            ativa: true },
  { id: 'qp-sagrado',     cnpj: '0001-89', nome: 'QP Sag Cor. Jesus - João Sampaio',           email: 'paroscj@outlook.com',                      ativa: true },
  { id: 'qp-antares',     cnpj: '0001-89', nome: 'QP Imaculado Coração de Maria - Antares',   email: '',                                         ativa: true },
  { id: 'santa-casa',     cnpj: '0001-89', nome: 'Capela Santa Casa de Misericordia',          email: '',                                         ativa: true },
  { id: 'candeias',       cnpj: '0001-89', nome: 'N Sra. das Candeias',                        email: '',                                         ativa: true },
  { id: 'palmares',       cnpj: '',        nome: 'Fundação Educadora Palmares',                 email: '',                                         ativa: true },
]
